import requests

API_URL = "http://192.168.0.85:11434/api/chat"


def ask_llm(prompt: str, model: str, think: bool = False) -> dict[str, str]:
    """Sends a prompt to the LLM and returns the evaluated response.
    
    Returns:
        A dictionary containing "content" and "thinking" generated by the model.
    """
    data = {
        "model": model,
        "stream": False,
        "messages": [{"role": "user", "content": prompt}],
        "think": think,
    }
    response = requests.post(API_URL, json=data)
    response.raise_for_status()
    message = response.json().get("message", {})
    content = message.get("content", "").strip()
    thinking = message.get("thinking", "").strip()

  
    return {
            "content": content,
            "thinking": thinking,
        }

